name: ApolloSpawners
author: DaRealPandaz [Owner] 
# - jaylac2000 [Editor] 
# - AdminConfirmed [Editor]
# - KielKing [Fixer]
version: 1.0.0
api: 3.11.2

^^ Some of this info is added just for the purpose of this github upload ^^
# Some info has also been removed 