name: ApolloMCPE
author: 
- KielKing 
- jaylac2000
- DaRealPandaz
- Shelly7w7
- diamondkorben
description: "ApolloMCPE"
softdepend: ["PurePerms", "EconomyAPI"]
serverip: play.apollomcpe.xyz
serverport: 19132
website: http://apollomcpe.buycraft.net/
vote: https://minecraftpocket-servers.com/server/87426/
discord: https://discord.gg/4MBsfTA
gamemodes: 
- Creative
- Skyblock
- Factions
- Survival
comingsoon:
- Prisons
- UHC
