name: ApolloSkyblock
api: 3.0.0
version: 1.0.4
author: AdminConfirmed - jaylac2000

^^ Some of this info is added just for the purpose of this github upload ^^
# Some info has also been removed 