name: AutoRestart
version: 1.0
api: 3.0.0
load: POSTWORLD
author: KielKing - jaylac2000
description: "ASC"

^^ Some of this info is added just for the purpose of this github upload ^^
# Some info has also been removed 